/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package boletin29;

import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author crist
 */
public class NewUser extends javax.swing.JFrame {

    /**
     * Creates new form NewUser
     */
    public NewUser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jNewUser = new javax.swing.JLabel();
        jUsername = new javax.swing.JLabel();
        jConfirm = new javax.swing.JLabel();
        jFullName = new javax.swing.JLabel();
        jUserID = new javax.swing.JLabel();
        jGroup1 = new javax.swing.JLabel();
        jHomeDirectory = new javax.swing.JLabel();
        jLoginShell = new javax.swing.JLabel();
        jPassword = new javax.swing.JLabel();
        tUser = new javax.swing.JTextField();
        tUserName = new javax.swing.JTextField();
        tFullName = new javax.swing.JTextField();
        tUserID = new javax.swing.JTextField();
        tConfirm = new javax.swing.JPasswordField();
        tPassword = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        bCancel = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jNewUser.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jNewUser.setText("Create a new user:");
        jPanel2.add(jNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 18, 170, 46));

        jUsername.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jUsername.setText("User name:");
        jPanel2.add(jUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jConfirm.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jConfirm.setText("Confirm:");
        jPanel2.add(jConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, -1));

        jFullName.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jFullName.setText("Full name:");
        jPanel2.add(jFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jUserID.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jUserID.setText("User ID:");
        jPanel2.add(jUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        jGroup1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jGroup1.setText("Group:");
        jPanel2.add(jGroup1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        jHomeDirectory.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jHomeDirectory.setText("Home Directory:");
        jPanel2.add(jHomeDirectory, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLoginShell.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLoginShell.setText("Login Shell:");
        jPanel2.add(jLoginShell, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        jPassword.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jPassword.setText("Password:");
        jPanel2.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, -1));

        tUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUserActionPerformed(evt);
            }
        });
        jPanel2.add(tUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 180, 30));
        tUser.getAccessibleContext().setAccessibleDescription("");

        tUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUserNameActionPerformed(evt);
            }
        });
        jPanel2.add(tUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 180, 30));

        tFullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFullNameActionPerformed(evt);
            }
        });
        jPanel2.add(tFullName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 180, 30));

        tUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUserIDActionPerformed(evt);
            }
        });
        jPanel2.add(tUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 180, 30));
        jPanel2.add(tConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 530, 150, 30));
        jPanel2.add(tPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 150, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Coordinador", "Miembro", "Encargado" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 150, 30));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User 1", "User 2", "User 3", "User 4" }));
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 170, 30));

        bCancel.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });
        jPanel2.add(bCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 570, 80, 50));

        jButton1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, 80, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUserActionPerformed

    private void tUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUserNameActionPerformed

    private void tFullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFullNameActionPerformed

    private void tUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tUserIDActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        /*
        Al pulsar el boton se borran los campos
        */
        tUserName.setText("");
        tConfirm.setText("");
        tFullName.setText("");
        tPassword.setText("");
        tUser.setText("");
        tUserID.setText("");
        //faltaría ver como borrar la selección de las ComboBox
    }//GEN-LAST:event_bCancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jConfirm;
    private javax.swing.JLabel jFullName;
    private javax.swing.JLabel jGroup1;
    private javax.swing.JLabel jHomeDirectory;
    private javax.swing.JLabel jLoginShell;
    private javax.swing.JLabel jNewUser;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jPassword;
    private javax.swing.JLabel jUserID;
    private javax.swing.JLabel jUsername;
    private javax.swing.JPasswordField tConfirm;
    private javax.swing.JTextField tFullName;
    private javax.swing.JPasswordField tPassword;
    private javax.swing.JTextField tUser;
    private javax.swing.JTextField tUserID;
    private javax.swing.JTextField tUserName;
    // End of variables declaration//GEN-END:variables
}
